elasticsearch:
  image: "elasticsearch:latest"
  expose:
    - "9200:9200"
  # volumes:
  #   - "$PWD/esdata:/usr/share/elasticsearch/data"
  #   - "$PWD/config:/usr/share/elasticsearch/config"
  restart: always

# logstash:
#   image: "logstash:latest"
#   volumes:
#     - "$PWD:/config-dir"
#   command: logstash -f /config-dir/logstash.conf

kibana:
  image: "kibana:latest"
  ports:
    - "80:5601"
  links:
    - "elasticsearch:elasticsearch"
  restart: always

# nginx:
#   image: "nginx:latest"
#   ports:
#     - "80:80"
#   volumes:
#     - "$PWD/conf/kibana.conf:/etc/nginx/nginx.conf:ro"
#   links:
#     - kibana:kibana
#   restart: always
